export const getStay = /* GraphQL */ `
  query GetStay($id: ID!) {
    getStay(id: $id) {
      id
      applicationID
      type
      state
      reservation_number
      payment_type
      PaymentTypeID
      payment_method {
        id
        name
        description
        status
        type
        createdAt
        updatedAt
      }
      payment_points_used
      payment_cost_of_reservation
      checkout_points_used
      checkout_cost_of_reservation
      requested_check_in
      requested_check_out
      status
      actual_check_in
      actual_check_out
      guest_stayed_at_hotel
      reason_guest_did_not_stay
      payment_incidental_cost
      charge_type
      card
      note
      reconciled
      ready_for_final_reconcile
      comment
      comparable_cost
      certificate_number
      confirmation_number
      card_used_for_incidentals
      room_type_requests
      room_feature_requests
      room_type_actual
      room_feature_actual
      room_description
      room_description_actual
      reason_decline
      reason_return
      charge_reconcile
      hotel_reconcile
      points_reconcile
      giftcard_reconcile
      batch_no
      city
      HotelPropertyID
      HotelBooked {
        id
        name
        address
        address_2
        city
        state
        zip
        contact_name
        contact_position
        telephone
        email
        is_blacklist
        status
        extension
        FisherHouseID
        HotelChainID
        HotelBrandID
        HotelBrand {
          logo
        }
        createdAt
        updatedAt
      }
      Application {
        id
        status
        liaison_read
        admin_read
        applicationPatientId
        applicationServiceMemberId
        exception_narrative
        liaison_terms_of_use_agreement
        sm_terms_of_use_agreement
        applicationGroupId
        AffiliationID
        createdAt
        updatedAt
        applicationUserId
        applicationAssignedToId
        applicationApplicantId
      }
      FisherHouse {
        id
        name
        type
        status
        display_name
        address
        address_2
        city
        state
        zip
        branch
        createdAt
        updatedAt
        affiliationAssociatedAffiliationId
        owner
      }
      narrative
      special_requests
      hotel_files {
        key
        user
      }
      notified_about_checkout
      createdAt
      updatedAt
      stayFisherHouseId
    }
  }
`;